GET http://localhost:4000

###
GET http://localhost:4000/abc

###
POST http://localhost:4000/user/register
Content-Type: application/json

{
  "email": "HIEUcuopbien125@gmail.com",
  "password": "123456"
}
###
POST http://localhost:4000/user/register
Content-Type: application/json

{
  "email": "HIEUcuopbien123@facebook.com",
  "password": "123456"
}
###
POST http://localhost:4000/user/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc3NTYzNDM4NjA1YWIyYTBkZWEwYzciLCJpYXQiOjE2ODU4NTA5NjMsImV4cCI6MTcxNzQwODU2M30.zXpjqJe19O238-G1W6BKwCBq6ycd2mAa5kwKCXID6nE"
}
###
POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "HIEUcuopbien125@gmail.com",
  "password": "123456"
}
###
POST http://localhost:4000/user/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc3NTYzNDM4NjA1YWIyYTBkZWEwYzciLCJpYXQiOjE2ODU4NTA5NjMsImV4cCI6MTcxNzQwODU2M30.zXpjqJe19O238-G1W6BKwCBq6ycd2mAa5kwKCXID6nE"
}
###
GET http://localhost:4000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDc3NTYzNDM4NjA1YWIyYTBkZWEwYzciLCJpYXQiOjE2ODU4NTA5NDUsImV4cCI6MTY4NTg1MTAwNX0.2VKKz9q8uXqIuOWzpasrm4otJGuZXstCdGNGhzLjtW0
